### ISSUE TITLE
ActivityNotFoundException

### ISSUE THREAD

**Issue by JuanIrache** [dandar3/android-google-play-billing#1]
Hi, Thanks for your project.

I'm trying to use it for my app's billing (migrating from an older in app purchases api version). I've made some progress, but when I try to make a purchase I get the following error:

> 06-14 19:32:39.309: E/AndroidRuntime(12630): android.content.ActivityNotFoundException: Unable to find explicit activity class {processing.test.gravity_playground/com.android.billingclient.api.ProxyBillingActivity}; have you declared this activity in your AndroidManifest.xml?

That's when I call

> BillingClient.launchBillingFlow(myActivity, purchaseParams);

Do you have any idea where my problem can be originating? Or where I could learn to implement the billing library in Eclipse?

Thanks!

**Comment by JuanIrache** [comment]
Nevermind. I copied the activity from your project's manifest to mine and it's working

**Comment by dandar3** [comment]
@JuanIrache 
Copying the activity is one way to do it.

The other is enabling the manifest merger for your Android app project to do all the work:
https://stackoverflow.com/a/11234525/308836

I meant to write a blogpost about it showing it in action for a project like Google Play Services or Firebase.
